<a href="https://colab.research.google.com/github/LamiaAlariqi/shi_task/blob/main/task1_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Create an array of 10 zeros
zeroes=np.zeros(10)
print(zeroes)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Create an array of 10 ones
one=np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Create an array of 10 fives
one=5*(np.ones(10))
print(one)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#Create an array of the integers from 10 to 50

ten_fifty=np.arange(10,51,1)
print(ten_fifty)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#Create an array of all the even integers from 10 to 50
ten_fifty_even=np.arange(10,51,2)
print(ten_fifty_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#find the memory size of any array
memory_size=ten_fifty_even.nbytes
print(memory_size)

168


In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8
threeXthree=np.arange(9)
threeXthree=threeXthree.reshape(3,3)
print(threeXthree)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Create a 3x3 identity matrix
identity=np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Use NumPy to generate a random number between 0 and 1
random=np.random.random()
print(random)

0.14429728239624895


In [ ]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
rand=np.random.randn(25)
print(rand)

[-0.61509752 -1.65113859 -0.79149285 -2.71720396 -1.26851009 -0.53941812
  1.09536056  1.4928619  -1.10093398  0.14339438  0.30744903  0.82936855
  0.5934709   0.88238175  0.28587884  0.33960634 -0.25582964  0.75884621
 -0.04913881  0.6733703   1.16773649 -1.37164821 -0.65105106  0.03877506
  0.50938189]


In [ ]:
#Create the following matrix:
arr=np.arange(0.01,1.01,0.01)
print(arr)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


In [ ]:
#Create an array of 20 linearly spaced points between 0 and 1:
linedspace=np.linspace(0,1,20)
print(linedspace)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
result = mat[2:5, 1:5]  #rows from 1 to 3 and columns from 1 to 4
print(result)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
twenty=mat[3,4]
print(twenty)

20


In [ ]:
result1=mat[0:3,1]
print(result1.reshape(3,1))

[[ 2]
 [ 7]
 [12]]


In [ ]:
result3=mat[4,0:5]
print(result3)

[21 22 23 24 25]


In [ ]:
result3=mat[3:5,0:5]
print(result3)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
sum1=mat.sum()
print(sum1.sum())

325


In [ ]:
dev=mat.std()
print(dev)

7.211102550927978


In [ ]:
sum_col=mat.sum(axis=0)
print(sum_col)

[55 60 65 70 75]


In [ ]:
matrix=np.zeros((10,10))
matrix[:,0]=1
matrix[-1,:]=1
matrix[0,:]=1
matrix[:,-1]=1
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
x1 = np.array([0, 2, 2, 2, 4, 5, 1, 4, 8, 5])
x2 = np.array([2, 2, 3, 4, 7, 4, 6, 9, 4, 8])

In [ ]:
common_values = np.intersect1d(x1, x2)
print(common_values)

[2 4 8]


In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x=x.flatten()
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Now pandas Exercies

In [ ]:
#import pandas
import pandas as pd

In [ ]:
#read the database as a dataframe
sal = pd.DataFrame(pd.read_csv("/content/Salaries.csv"))


<ipython-input-32-344d571c81b3>:2: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.DataFrame(pd.read_csv("/content/Salaries.csv"))


In [ ]:
#check the head of the dataframe
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

     Year  Notes         Agency Status  
0  2011.0    NaN  San Francisco    NaN  
1  2011.0    NaN  San Francisco    NaN  
2  2011.0    NaN  San Francisco    NaN  
3  2011.0    NaN  San Francisco    NaN  
4  2011.0    NaN  San Francisco    NaN

In [ ]:
#What is the average BasePay ?
unique_values = sal['BasePay'].unique()
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce') #convert to numeric
avg=sal['BasePay'] .mean()
print(avg)

66325.4488404877


In [ ]:
# What is the highest amount of OvertimePay in the dataset ? **
unique_values = sal['BasePay'].unique()
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors='coerce') #convert to numeric
max=sal['OvertimePay'].max()
print(max)

245131.88


In [ ]:
#What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).
job_title = sal.loc[sal['EmployeeName'] == 'JOSEPH DRISCOLL', 'JobTitle']
print(job_title)

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object


In [ ]:
#How much does JOSEPH DRISCOLL make (including benefits)? **
salary=sal.loc[sal['EmployeeName']=='JOSEPH DRISCOLL','TotalPayBenefits']
print(salary)

24    270324.91
Name: TotalPayBenefits, dtype: float64


In [ ]:
#** What is the name of highest paid person (including benefits)?**
highest=sal.loc[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]
highest_df = pd.DataFrame(highest)
print(highest_df)

   Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   

   Year  Notes         Agency Status  TitleLength  
0  2011    NaN  San Francisco    NaN           46  


In [ ]:
#** What is the name of lowest paid person (including benefits)?**
lowest=sal.loc[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]
print(lowest)

            Id EmployeeName                    JobTitle BasePay OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch    0.00        0.00   

       OtherPay Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653  -618.13     0.00   -618.13           -618.13  2014    NaN   

               Agency Status  
148653  San Francisco     PT  


In [ ]:
#What was the average (mean) BasePay of all employees per year? (2011-2014) ? **
uni=sal['BasePay'].unique()
sal['BasePay']=pd.to_numeric(sal['BasePay'],errors='coerce')
sal_filtered = sal[(sal['Year'] >= 2011) & (sal['Year'] <= 2014)]

# Calculate the average BasePay per year
average_basepay_by_year = sal_filtered.groupby('Year')['BasePay'].mean()

print(average_basepay_by_year)

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64


In [ ]:
#How many unique job titles are there? ** Read about the "nunique" function
unique=sal['JobTitle'].nunique()
print(unique)

2159


In [ ]:
#** What are the top 5 most common jobs? **
job_c = sal['JobTitle'].value_counts()
top_5_jobs = job_c.head(5)
print(top_5_jobs)

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64


In [ ]:
# How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **
y2013 = sal[sal['Year'] == 2013]
job = y2013['JobTitle'].value_counts()
job_count = sum(job== 1)
print(job_count)


202


In [ ]:
#How many people have the word Chief in their job title? (This is pretty tricky) **
chief_count = sal[sal['JobTitle'].str.contains('Chief', case=False)].shape[0]  #for both chief and Chief
print(chief_count)

627


In [ ]:
#Is there a correlation between length of the Job Title string and Salary? **
sal['TitleLength'] = sal['JobTitle'].str.len()
correlation = sal['TitleLength'].corr(sal['TotalPayBenefits'])
correlation_df = pd.DataFrame({'title_len': [1.0, correlation],
                               'TotalPayBenefits': [correlation, 1.0]},
                              index=['title_len', 'TotalPayBenefits'])

print(correlation_df)

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000
